/** Field name → inspector tab. Unlisted fields default to Content. */
const FIELD_GROUPS = {
  displayName: 'content',
  text: 'content',
  label: 'content',
  level: 'content',
  url: 'content',
  imageUrl: 'content',
  imageAlt: 'content',
  videoUrl: 'content',
  posterUrl: 'content',
  controls: 'content',
  shape: 'content',
  buttonStyle: 'content',
  logoUrl: 'content',
  title: 'content',
  subtitle: 'content',
  eyebrow: 'content',
  ctaLabel: 'content',
  ctaUrl: 'content',
  links: 'content',
  items: 'content',
  buttons: 'content',
  speakers: 'content',
  sponsors: 'content',
  testimonials: 'content',
  stats: 'content',
  faq: 'content',
  photos: 'content',
  body: 'content',
  heading: 'content',
  description: 'content',
  navLinks: 'content',

  colour: 'style',
  fill: 'style',
  backgroundColour: 'style',
  backgroundImage: 'style',
  textColour: 'style',
  fontSize: 'style',
  opacity: 'style',
  thickness: 'style',
  objectFit: 'style',
  lockAspectRatio: 'style',
  align: 'style',
  primaryColour: 'style',
  secondaryColour: 'style',
  font: 'style',
  designDirection: 'style',

  layoutMode: 'layout',
  flowArrangement: 'layout',
  flowGap: 'layout',
  flowAlign: 'layout',
  flowColumns: 'layout',
  contentWidth: 'layout',
  minHeight: 'layout',
  padding: 'layout',
  gap: 'layout',
  arrangement: 'layout',
  snapEnabled: 'layout',
  snapGrid: 'layout',
  mobileLayout: 'layout',
  resetMobile: 'layout',
  x: 'layout',
  y: 'layout',
  width: 'layout',
  height: 'layout',
  heightMode: 'layout',
  zIndex: 'layout',
  locked: 'layout',
  mobileX: 'layout',
  mobileY: 'layout',
  mobileWidth: 'layout',
  mobileHeight: 'layout',
  mobileHeightMode: 'layout',
  spacing: 'layout',
};

export const INSPECTOR_TABS = [
  { id: 'content', label: 'Content' },
  { id: 'style', label: 'Style' },
  { id: 'layout', label: 'Layout' },
];

export function groupForField(fieldName) {
  return FIELD_GROUPS[fieldName] || 'content';
}

export const displayNameField = {
  type: 'text',
  label: 'Display name',
};
